### PR TITLE
[#1822] Add template for ATAS correspondence

### LINKED ISSUE #1822: Provide canned removal message for ATAS
We're seeing an uptick in ["ATAS"](https://www.gov.uk/guidance/academic-technology-approval-scheme) related messages, which relate to individuals personal circumstances.

At the moment, the generic templates on Alaveteli don't cover the specific information that is helpful to convey to individuals, so it is time consuming to carry out admin actions on these requests.

We could, perhaps, use a [variant of the setup for immigration related matters](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/admin_request/_hidden_user_explanation_reasons.html.erb) (body `93723`).

### PR DESCRIPTION
**Pull request by mdeuk**
## Relevant issue(s)

Fixes #1822
Depends on https://github.com/mysociety/alaveteli/pull/8121

## What does this do?

This adds a new template `Immigration correspondence (ATAS)` which displays on requests made to body `93723` (FCDO).

## Why was this needed?

There has been an uptick in requests to the FCDO which concern a specific immigration matter (ATAS), and this is not covered by the existing messages for this body.

## Implementation notes

Nothing special to note.

## Notes to reviewer

When testing this on a sandbox, I'm getting a weird glitch where it looks like every line is double spaced (e.g. `\n\n`). I think this is a problem with _my environment_, as it does the same with others (e.g. `_subject_access_request`), but it seemed worth noting anyway.

### CODE REVIEW

**Comment by mdeuk** [comment]
Sorry, looks like my base was out of date - despite git originally claiming otherwise. Hopefully I've not broken anything.

**Review by gbp — CHANGES_REQUESTED** [review]
This is great. I have created https://github.com/mysociety/alaveteli/pull/8121 so we can use conditionals to render different content for prominence reason.

Once that is merged, I'll commit/merge, and deploy:
```diff
diff --git a/lib/views/admin_request/hidden_user_explanation/_immigration_correspondence_atas.text.erb b/lib/views/admin_request/hidden_user_explanation/_immigration_correspondence_atas.text.erb
index a987341..2d5fb24 100644
--- a/lib/views/admin_request/hidden_user_explanation/_immigration_correspondence_atas.text.erb
+++ b/lib/views/admin_request/hidden_user_explanation/_immigration_correspondence_atas.text.erb
@@ -2,12 +2,13 @@
       'circumstances, via our service, and we have therefore hidden it ' \
       'from other users.') %>
 
-<%= _('👉 Getting the help you need' \
+<% if explanation %>
+<%= _('👉 Getting the help you need ' \
       '{{site_name}} is an independent website which helps people make ' \
       'Freedom of Information requests in public. We are not part of the ' \
       'Government.',
       site_name: site_name) %>
-      
+
 <%= _('You should contact the Foreign, Commonwealth, and Development Office '\
       '(FCDO) directly. They are the department responsible for the ATAS '\
       'scheme. ') %>
@@ -48,4 +49,5 @@ https://www.citizensadvice.org.uk/about-us/contact-us/contact-us/contact-us/
       'to misuse our service, we wanted to remind you of our house rules, '\
       'which are the conditions of use for our service.'\
       'You can find them at: {{help_house_rules}}',
-      help_house_rules: help_house_rules_url) %>
\ No newline at end of file
+      help_house_rules: help_house_rules_url) %>
+<% end %>
```

**Comment by WilliamWDTK** [comment]
There are a few textual changes I would make, referencing the parts marked in red in the image above (and text just by that section).

1. `circumstances, via` → `circumstances via`
2. `needWhatDoTheyKnow`: add line-break
3. `Foreign, Commonwealth, and Development Office` → at least `Foreign, Commonwealth and Development Office`, but ideally match official name and [WDTK listing](https://www.whatdotheyknow.com/body/fcdo) with `Foreign, Commonwealth & Development Office`
4. `directly, at: atas@fcdo.gov.uk`: might want to remove colon and add full stop, that's possibly personal preference.
5. `MPs offices can ask the FCDO` → `MPs' offices can ask the FCDO`
6. `You will still be able to view it while logged in to the site.` → `You will still be able to view the request while logged into the site.` (The mention of hiding was much earlier, so it's not clear what `it` is referring to, also `in to` → `into`.)

**Comment by gbp** [comment]
Thanks @WilliamWDTK I have made those changes (except for 6 as that requires a change in core Alaveteli codebase)

Updated screenshots:

Screenshot 2024-02-09 at 11-57-15 FOI request – Test request - WhatDoTheyKnow admin
Screenshot 2024-02-09 at 11 58 25
Screenshot 2024-02-09 at 11 59 19
Screenshot 2024-02-09 at 11 59 45

**Comment by gbp** [comment]
Merged in 56d2d5b

**Pull request closed without merging**
