### PR TITLE
Redesign site header

### PR DESCRIPTION
**Pull request by wrightmartin**
This is the groundwork for the new design of the site header, along with #195 and #193 

It sets up the new design layout and spacing, but uses the current themes' type and colours, to be changed at a later date

Part of https://github.com/mysociety/alaveteli/issues/1525 

screen shot 2015-05-19 at 09 32 28
screen shot 2015-05-19 at 09 32 21

### CODE REVIEW

**Comment by garethrees** [comment]
Looks so much better!

Summary of fixes:

- [ ] Cleanly remove mistakenly committed merge conflict marker
- [ ] Nav items overlap banner shadow
- [ ] Consider using existing logo for compatibility with existing branding

**Comment by garethrees** [comment]
Locale switcher needs some tweaks to work with the new banner:

screen shot 2015-06-04 at 10 23 32

screen shot 2015-06-04 at 10 23 37

**Comment by wrightmartin** [comment]
This is now ready again

screen shot 2015-06-05 at 08 32 19
screen shot 2015-06-05 at 08 32 11

**Comment by garethrees** [comment]
Looking good.

I think the hover colour on the locale switcher needs to be a touch darker. Very similar to the banner:

screen shot 2015-06-05 at 11 05 22

The search box is a bit weird for me:

screen shot 2015-06-05 at 11 05 29

Magnifying glass is on the left and I have the word "Search" in the box, in a very light grey colour.

**Comment by garethrees** [comment]
The logged in view doesn't look _awesome_ – I'll merge and deploy this as is and we'll address the logged in nav independently.

**Pull request merged**
