### PR TITLE
Create glossary

### PR DESCRIPTION
**Pull request by confirmordeny**
Work in progress

### CODE REVIEW

**Comment by confirmordeny** [comment]
Working on a glossary

**Comment by mdeuk** [comment]
This looks great so far, thank you for doing it @confirmordeny!

Just a small note: I think the extension has dropped off the filename in https://github.com/mysociety/whatdotheyknow-theme/commit/72ec75c0a41be2db07397c10dd0b83ed94a20abc - it should be `glossary.html.erb`.

**Comment by confirmordeny** [comment]
Thank you mdeuk. I am still learning how this works. I have tried again.

**Comment by mdeuk** [comment]
> Thank you mdeuk. I am still learning how this works. I have tried again.

As am I, every day is a school day! 😃

**Pull request closed without merging**
