### PR TITLE
Add UK-specific excluded calculated homepage domains

### PR DESCRIPTION
**Pull request by garethrees**
Requires https://github.com/mysociety/alaveteli/pull/7836

### CODE REVIEW

**Comment by garethrees** [comment]
Any more we want to catch? Don't need to be exhaustive at this point, but might have missed a few obvious ones.

**Comment by gbp** [comment]
@garethrees the specs are failing on this guessing that is because the core PR hasn't been merged. Attempting to run this locally and it doesn't seem to be working, am I missing something?

**Comment by gbp** [comment]
```ruby
[1] pry(main)> PublicBody.excluded_calculated_home_page_domains
=> ["aol.com",
 "gmail.com",
 "googlemail.com",
 "gmx.com",
 "hotmail.com",
 "icloud.com",
 "live.com",
 "mac.com",
 "mail.com",
 "mail.ru",
 "me.com",
 "outlook.com",
 "protonmail.com",
 "qq.com",
 "yahoo.com",
 "yandex.com",
 "ymail.com",
 "zoho.com",
 ["aol.co.uk",
  "blueyonder.co.uk",
  "btconnect.com",
  "btinternet.com",
  "btopenworld.com",
  "hotmail.co.uk",
  "live.co.uk",
  "ntlworld.com",
  "sky.com",
  "talk21.com",
  "talktalk.net",
  "tiscali.co.uk",
  "virginmedia.com",
  "yahoo.co.uk"]]
```

**Comment by garethrees** [comment]
Ah, woops!

**Pull request merged**
