### PR TITLE
Sidebars now look like the reference design

### PR DESCRIPTION
**Pull request by wrightmartin**
Improved spacing, typography and button layout

### Before
screen shot 2015-06-12 at 09 44 36

### After
screen shot 2015-06-12 at 09 44 42

### CODE REVIEW

**Comment by garethrees** [comment]
I think the small headings have made it less clear. They don't divide the sections as well, so it all looks like one long sidebar. I think the headings need to be a bit bigger and bolder (I like the style, though!) and the rest of the text needs to be smaller (in proportion to the headings).

**Comment by garethrees** [comment]
> Sidebars now look like the reference design

Is there a specific design mockup for the sidebars anywhere, or do you just mean in terms of fitting in with the homepage mockup? (#212)

**Comment by wrightmartin** [comment]
@garethrees here's the design this comes from

screen shot 2015-06-12 at 12 09 04

**Comment by wrightmartin** [comment]
Improvement?

screen shot 2015-06-12 at 14 01 21

**Comment by garethrees** [comment]
Definitely better, but I think the problem still exists.

Maybe like this?

screen shot 2015-06-12 at 14 34 08

I still think it looks a bit busy, but I think the font proportions are better.

**Comment by wrightmartin** [comment]
The trick with that type of heading design (capped up) is too keep it smaller than the body text, it looks neat. As soon as it gets bigger than or equal to, it should be normal case to stop it looking clumsy.

**Comment by garethrees** [comment]
> The trick with that type of heading design (capped up) is too keep it smaller than the body text, it looks neat. As soon as it gets bigger than or equal to, it should be normal case to stop it looking clumsy.

Yeah, I don't disagree. I just think that in the current sidebar the small headings get totally lost.

**Comment by garethrees** [comment]
Okay so we could start from the point of tidying up the existing related request listing:

- make them a bit smaller
- small grey date to match homepage
- display block on the dates to always put them on a newline

screen shot 2015-06-12 at 14 59 10

**Comment by wrightmartin** [comment]
> Okay so we could start from the point of tidying up the existing related request listing:
>
> - make them a bit smaller
> - small grey date to match homepage
> - display block on the dates to always put them on a newline

Yep, a fine idea

screen shot 2015-06-12 at 19 15 09

**Pull request merged**
