### PR TITLE
[#358] implement the action menu

### LINKED ISSUE #358: Add action menu code to overridden templates
includes
- request/_sidebar.html.erb
- request/_show.html.erb

Also needs to adopt the extra help page sections from https://github.com/mysociety/alavetelitheme/pull/86

Connects to https://github.com/mysociety/alaveteli/issues/3412

### PR DESCRIPTION
**Pull request by lizconlan**
Alters the overrides to allow the action menus to work properly (and the link to appear at the top rather than the foot of the page).

Closes #358

### CODE REVIEW

**Comment by lizconlan** [comment]
(I've found a couple of typos in `request/show` morning while comparing against alavetelitheme, expect fixup commit)

**Comment by lizconlan** [comment]
fixed, now includes bonus commit including the blank authority search code from https://github.com/mysociety/alaveteli/commit/1509236

**Comment by garethrees** [comment]
Cheers – pulled in to https://github.com/mysociety/whatdotheyknow-theme/pull/361 as there were some other changes that needed to get resolved too.

**Comment by lizconlan** [comment]
neat, I'll close #358 as well

**Pull request closed without merging**
