### PR TITLE
Improve logged in experience

### LINKED ISSUE #205: Improve logged-in nav
https://github.com/mysociety/alaveteli/issues/1525

Made no worse by https://github.com/mysociety/whatdotheyknow-theme/pull/197, but doesn't look as good as the new stuff.

screen shot 2015-06-05 at 11 30 20

### PR DESCRIPTION
**Pull request by wrightmartin**
Closes #205, #206

### CODE REVIEW

**Comment by garethrees** [comment]
I wonder if we should section up the mobile nav like this:

screen shot 2015-06-11 at 10 15 47

At the moment its not that clear that each group is related to a specific set of actions.

**Comment by wrightmartin** [comment]
@garethrees :+1: yep, I agree

**Comment by garethrees** [comment]
> If it doesn't add anything to the mobile experience, does it add anything to the desktop?

I guess the main point is to show you're logged in as the person you're expecting to be logged in as.

Question is, can we do this any better than what's there now? I expect this is more a question for alaveteli core than the WDTK theme?

**Comment by wrightmartin** [comment]
@garethrees, yes, we should make a ticket there, shall I hide it here for now?

**Comment by garethrees** [comment]
I think we just keep it for now. Lets divide up the nav sections on mobile because that makes sense to do, and then deploy the rest as-is.

**Pull request merged**
