### PR TITLE
Change typeface

### PR DESCRIPTION
**Pull request by wrightmartin**
This switches out the old typeface (Ubuntu?) for mySociety's brand typeface (Source Sans)

### Before
screen shot 2015-06-10 at 16 46 32

### After
screen shot 2015-06-10 at 16 45 37

### CODE REVIEW

**Comment by garethrees** [comment]
At around 750px wide:

screen shot 2015-06-11 at 11 05 44

**Comment by garethrees** [comment]
Just minor fix to the how it works section, but otherwise :+1: 

I actually prefer Helvetica Neue (or even Arial), but +1 for consistency across sites.

**Comment by garethrees** [comment]
I think this has knocked the button text out of alignment too:

screen shot 2015-06-11 at 14 34 14

**Comment by wrightmartin** [comment]
> I think this has knocked the button text out of alignment too:

I'm not too worried about that, as the next PR will be all-new buttons

**Comment by wrightmartin** [comment]
> 939px:

I can't reproduce it  :(

**Comment by garethrees** [comment]
okay we'll launch it as is and see if we can fix it later

**Comment by garethrees** [comment]
Merged in https://github.com/mysociety/whatdotheyknow-theme/commit/0b162ef70727a7234adfd2ac27b221e08f371950

**Pull request closed without merging**
