### PR TITLE
Remove exception template override.

### PR DESCRIPTION
**Pull request by crowbot**
Once the changes made in 416ad02a6d01b2e6cdbcc94e7bd143c9c21e59c6
are made here, it would be identical to the template in core.

### CODE REVIEW

**Comment by lizconlan** [comment]
:+1: yay, fewer overrides!

**Comment by lizconlan** [comment]
looks as though mysociety/alaveteli@416ad02a6d01b2e6cdbcc94e7bd143c9c21e59c6 has made it into develop, not sure whether it's been deployed to wdtk

**Comment by garethrees** [comment]
The view still exists in master: https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/general/exception_caught.html.erb. Looks like this got closed without merging?

**Comment by garethrees** [comment]
Ah cool 👍

**Pull request closed without merging**
