### PR TITLE
1706 add a help page on exemptions

### PR DESCRIPTION
**Pull request by HelenWDTK**
## Relevant issue(s)
#1706
## What does this do?
Adds a help page about the various FOI and FOISA exemptions, with links to guidance
## Why was this needed?
We had no way of linking users to guidance on specific issues. Help people to understand what they can and can't get released under FOI
## Screenshots
Screenshot 2023-06-14 at 14 37 44
Screenshot 2023-06-14 at 14 38 01
Screenshot 2023-06-14 at 14 38 13

### CODE REVIEW

**Comment by HelenWDTK** [comment]
I've tested the links here, and everything looks good. One point of detail: I describe s36 as only having a PIT sometimes, due to the fact that a qualified person can issue a certificate. It might be that we want to amend that to say yes.

**Review by garethrees — APPROVED** [review]
Looks amazing!

Only suggestion would be to add a line at the top pointing people to `/help/unhappy` and our refusal advice there.

**Comment by HelenWDTK** [comment]
Added the link. The wording is not the best, but borrowed from elsewhere on the help pages, so if we want to fix it, we should prob. fix both.

**Comment by garethrees** [comment]
Yeah works well enough for now 👍

**Pull request merged**
