### PR TITLE
Move locale switcher

### PR DESCRIPTION
**Pull request by wrightmartin**
This moves the locale switcher to the right of the logo, part of the much bigger https://github.com/mysociety/alaveteli/issues/1525 

The final commit needs some dev work, I've left a line comment. 

Screenshots:

screen shot 2015-05-08 at 14 27 31
screen shot 2015-05-08 at 14 27 35

screen shot 2015-05-08 at 14 27 22
screen shot 2015-05-08 at 14 27 25

### CODE REVIEW

**Comment by garethrees** [comment]
screen shot 2015-05-12 at 15 20 00

The available locale box could do with a touch more vertical padding IMO

**Comment by garethrees** [comment]
I don't think its a big problem since we only have English and Welsh, but it looks strange when it overlaps the nav:

screen shot 2015-05-12 at 15 21 07

Something to keep in mind.

**Comment by garethrees** [comment]
@wrightmartin I've squashed everything in to one commit. Could you just check its as expected?

**Comment by wrightmartin** [comment]
Yep, this works as expected, go for it :+1:

**Comment by garethrees** [comment]
> Pull down width is a bit untidy

We can address this when integrating it in to #197

**Pull request merged**
