### PR TITLE
Mysociety 20th anniversary

### PR DESCRIPTION
**Pull request by lucascumsille**
For the Desktop versions I have created to versions
Let me know which one you prefer 

### Badge slightly overlapping second navbar

Screenshot 2023-02-15 at 11 34 26

### Badge 3px wider so the rectangle part of the badge matches the main navbar height. No overlapping with elements below.
Screenshot 2023-02-15 at 11 55 08

---
### Mobile

Screenshot 2023-02-15 at 11 34 55

### CODE REVIEW

**Review by zarino — APPROVED** [review]
Haven’t tested this out locally, but the code looks sensible. I’d go with the second option you presented, where the left edge of the first nav link lines up with the left edge of the WhatDoTheyKnow logo. 👍

**Review by gbp — CHANGES_REQUESTED** [review]
Issue with the Pro version of the site:

image

**Comment by lucascumsille** [comment]
Thanks for @gbp I just added a commit for that. 
I found another issue with the sign in button, being too dark the second commit tackles that, not sure if we want to include it in this PR.

Screenshot 2023-03-08 at 12 42 35
Screenshot 2023-03-08 at 12 42 44
Screenshot 2023-03-08 at 12 47 55
Screenshot 2023-03-08 at 12 58 21

**Review by gbp — APPROVED** [review]
Nice one this looks good now. I have cherry picked 7e055973d9e109012af85d8002351f816b6f0b5f into master already as we want to be able to revert this branch when we remove the 20th anniversary banner.

**Pull request merged**
