### PR TITLE
Create glossary.html.erb

### PR DESCRIPTION
**Pull request by confirmordeny**
## Relevant issue(s)
Create a glossary to help demystify some of the abbreviations and special terms used by FOI officers and transparency campaigners. Explains terms used in our help pages and elsewhere on the site.

## What does this do?
See above.

## Why was this needed?
See above.

## Implementation notes
Once this goes live, certain terms on the help pages can be linked to these definitions.

## Screenshots
N/A

### CODE REVIEW

**Comment by confirmordeny** [comment]
I think the glossary is in quite a good place now. If it is added some more work would be needed to ensure good linkage between the help pages.

**Comment by garethrees** [comment]
Amazing – will get this reviewed and merged as soon as we can.

**Comment by gbp** [comment]
Needed minor changes to get this rendered correctly and linked from the sidebar.

image

**Review by gbp — APPROVED** [review]
Great work. Thanks

**Pull request merged**
