### PR TITLE
replace logo with new colourway

### PR DESCRIPTION
**Pull request by wrightmartin**

### CODE REVIEW

**Comment by garethrees** [comment]
:hotsprings: :+1:

**Comment by garethrees** [comment]
Bah just merged this but noticed the file size has doubled!

```
assets/images/navimg/logo-trans-small.png | Bin 4505 -> 9644 bytes
```

@wrightmartin anything you can do about that? http://kraken.io?

**Comment by wrightmartin** [comment]
Yeah I'll recompress it and push again

**Comment by garethrees** [comment]
That would be an awesome check to have. We don't actually run CI on themes (https://github.com/mysociety/alaveteli/issues/1853) but might still be worth adding to alaveteli itself

**Pull request merged**
