### PR TITLE
Change colour scheme

### PR DESCRIPTION
**Pull request by wrightmartin**
This updates the colour scheme of WDTK to the new one, using mySociety colours

### Before
screen shot 2015-06-11 at 11 19 52

### After
screen shot 2015-06-11 at 11 19 46

### CODE REVIEW

**Comment by garethrees** [comment]
Going to wait until #215 is merged before reviewing, as this will need rebasing once its merged.

**Comment by garethrees** [comment]
On the whole, massive :+1:!

I'd like to merge #217 first so that the colour change has all the nice bits in place.

I prefer the blue on the original mockup (right):

screen shot 2015-06-12 at 09 41 30

It feels a little more serious and gets out of the way. I find the blue in this PR is a little too distracting.
I'd also go for more conservative colours for the correspondence boxes, but I don't have as much of a strong feeling on that one.

**Comment by garethrees** [comment]
We've lost a bit of contrast on the "Currently waiting for a response…" line:

screen shot 2015-06-12 at 09 55 31

screen shot 2015-06-12 at 09 59 12

Doesn't look quite as bad in the screenshot but its a little tough to read on my screen

**Comment by wrightmartin** [comment]
> It feels a little more serious and gets out of the way. I find the blue in this PR is a little too distracting.
I'd also go for more conservative colours for the correspondence boxes, but I don't have as much of a strong feeling on that one.

For some reason the blue I used on the mockups wasn't the 'official' blue, so I've used the official one in the design, but I totally see what you mean, I've opened a ticket #218 that will have some tweaks to the colour in the nav bar and that should help bring it down a bit

>We've lost a bit of contrast on the "Currently waiting for a response…" line:

I'll darken this before we merge

**Comment by wrightmartin** [comment]
Here's the new darker orangge

screen shot 2015-06-12 at 11 19 30

**Comment by wrightmartin** [comment]
Before and after of the different blue in the header

screen shot 2015-06-12 at 11 21 07

**Comment by wrightmartin** [comment]
Okay, here's a big revision to the colours 

screen shot 2015-06-12 at 13 44 05

**Comment by garethrees** [comment]
Yeah, that's a lot better.

Not keen on the button hover:

screen shot 2015-06-12 at 14 38 07

Some "buttons" don't change much when hovered over:

blue-button-hover

**Comment by garethrees** [comment]
Couldn't sell you on a slightly more muted correspondence thread could I?
screen shot 2015-06-12 at 14 49 44

**Comment by wrightmartin** [comment]
> Some "buttons" don't change much when hovered over:

Just needed a tweak after I darkened down the blue, should be better now

**Pull request merged**
